# Generated by Django 4.1.12 on 2024-05-22 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForexSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SymbolAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('kvo', models.FloatField(blank=True, null=True)),
                ('signal', models.FloatField(blank=True, null=True)),
                ('hist', models.FloatField(blank=True, null=True)),
                ('sl_price', models.FloatField(blank=True, null=True)),
                ('tp_price', models.FloatField(blank=True, null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.forexsymbol')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('order_type', models.CharField(max_length=4)),
                ('volume', models.FloatField()),
                ('sl_price', models.FloatField()),
                ('tp_price', models.FloatField()),
                ('order_number', models.PositiveIntegerField()),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.forexsymbol')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='symbol',
        ),
        migrations.DeleteModel(
            name='HistoricalData',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Symbol',
        ),
    ]
